/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Modelo.Client;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author alexander
 */
public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    
    Client client = new Client();
    private final ArrayList<ArrayList<String>> listas;
    
    
    public Factura() 
    {
        initComponents();
                listas = client.carga();
        insertarCB(jComboBox_Cliente, client.cargaCliente());
        insertarCB(jComboBox_Producto, client.cargaProducto());
        insertarCB(jComboBox_Sucursal, client.cargaSucursal());
        insertarCB(jComboBox_TipoPago, client.cargaTipoPago());
        insertarCB(jComboBox_Empleados, client.cargaEmpleado());
    }
    double porcentaje = 0.16;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Insertar = new javax.swing.JPanel();
        jTextField_CantidadProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_Producto = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_TipoPago = new javax.swing.JComboBox();
        jComboBox_Cliente = new javax.swing.JComboBox();
        jComboBox_Sucursal = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel_ValorTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_Execute = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel_IVA = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_Empleados = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextField_CantidadProducto.setText("0");

        jLabel1.setText("Cantidad:");

        jLabel2.setText("Tipo de Pago:");

        jLabel3.setText("Cliente:");

        jComboBox_Producto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ProductoItemStateChanged(evt);
            }
        });
        jComboBox_Producto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox_ProductoFocusLost(evt);
            }
        });

        jLabel4.setText("Producto:");

        jLabel5.setText("Sucursal:");

        jLabel_ValorTotal.setText("0");

        jLabel7.setText("Total Venta:");

        jButton_Execute.setText("Carga");
        jButton_Execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExecuteActionPerformed(evt);
            }
        });

        jLabel8.setText("IVA:");

        jLabel_IVA.setText("0");

        jLabel6.setText("Empleado:");

        javax.swing.GroupLayout jPanel_InsertarLayout = new javax.swing.GroupLayout(jPanel_Insertar);
        jPanel_Insertar.setLayout(jPanel_InsertarLayout);
        jPanel_InsertarLayout.setHorizontalGroup(
            jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InsertarLayout.createSequentialGroup()
                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InsertarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel_InsertarLayout.createSequentialGroup()
                                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_ValorTotal)
                                    .addComponent(jComboBox_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_IVA)))
                            .addGroup(jPanel_InsertarLayout.createSequentialGroup()
                                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_InsertarLayout.createSequentialGroup()
                                        .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(131, 131, 131))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_InsertarLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_CantidadProducto)
                                    .addComponent(jComboBox_Cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Sucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_TipoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Empleados, 0, 176, Short.MAX_VALUE)))))
                    .addGroup(jPanel_InsertarLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton_Execute))
                    .addGroup(jPanel_InsertarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel_InsertarLayout.setVerticalGroup(
            jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InsertarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_CantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ValorTotal)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_IVA)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_TipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jButton_Execute)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ProductoItemStateChanged

    }//GEN-LAST:event_jComboBox_ProductoItemStateChanged

    private void jComboBox_ProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_ProductoFocusLost
        ArrayList<String> t = listas.get(8);

        jLabel_IVA.setText(null);

        double rta = Double.parseDouble(t.get(jComboBox_Producto.getSelectedIndex())) * Double.parseDouble(jTextField_CantidadProducto.getText());
        jLabel_ValorTotal.setText(rta + "");

        jLabel_IVA.setText((rta*porcentaje) + "");
    }//GEN-LAST:event_jComboBox_ProductoFocusLost

    private void jButton_ExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExecuteActionPerformed

        String cantidad = jTextField_CantidadProducto.getText();
        int producto = jComboBox_Producto.getSelectedIndex() + 1;
        int tipoPago = jComboBox_TipoPago.getSelectedIndex() + 1;
        int cli = jComboBox_Cliente.getSelectedIndex() + 1;
        int suc = jComboBox_Sucursal.getSelectedIndex() + 1;
        int emp = jComboBox_Empleados.getSelectedIndex() + 1;

        double calcTotal = Double.parseDouble(jLabel_ValorTotal.getText()) + Double.parseDouble(jLabel_IVA.getText());

        String data = cantidad + ";" + calcTotal + ";" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()) + ";" + jLabel_IVA.getText() + ";" + tipoPago + ";" + cli + ";" + emp + ";" + suc + ";" + producto + ";" + cantidad;
        client.insertarVenta(data);
        JOptionPane.showMessageDialog(null, "Operacion realizada");
    }//GEN-LAST:event_jButton_ExecuteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        client.cerrarSesion();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Factura().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Execute;
    private javax.swing.JComboBox jComboBox_Cliente;
    private javax.swing.JComboBox jComboBox_Empleados;
    private javax.swing.JComboBox jComboBox_Producto;
    private javax.swing.JComboBox jComboBox_Sucursal;
    private javax.swing.JComboBox jComboBox_TipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_IVA;
    private javax.swing.JLabel jLabel_ValorTotal;
    private javax.swing.JPanel jPanel_Insertar;
    private javax.swing.JTextField jTextField_CantidadProducto;
    // End of variables declaration//GEN-END:variables

    private void insertarCB(JComboBox seleccion, ArrayList<String> lista) 
    {
        lista.stream().forEach((s) -> 
        {
            if (s.contains(";"))
            {
                String[] temp = s.split(";");
                seleccion.addItem(temp[temp.length-1]);
            }
            else
            {
                seleccion.addItem(s);
            }
        });
    }
}
