/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Modelo.Client;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author alexander
 */
public class PrincipalMenu extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalMenu
     */
    
            private File f;
    private BufferedImage image;
    Client client = new Client();
    
    public PrincipalMenu() {
        initComponents();
        imagen("imagenes\\nuevaventa.png");
        jLabel_nuevaVenta.setIcon(new ImageIcon(f.getAbsolutePath()));
        
                imagen("imagenes\\ventasporciudad.png");
        jLabel_VentasCiudad.setIcon(new ImageIcon(f.getAbsolutePath()));
        
                imagen("imagenes\\ventasporcliente.png");
        jLabel_VentasCliente.setIcon(new ImageIcon(f.getAbsolutePath()));
        
                imagen("imagenes\\cuentasporcobrar.png");
        jLabel_CuentasCobrar.setIcon(new ImageIcon(f.getAbsolutePath()));
        
                imagen("imagenes\\productos.png");
        jLabel_Admin.setIcon(new ImageIcon(f.getAbsolutePath()));
        
    }
        public final void imagen(String archivo) 
	{
            try 
            {
                f = new File(archivo);
                image = ImageIO.read(f);
            } 
            catch (IOException ie) 
            {
                System.out.println("Error: " + ie.getMessage() + " " + f.getName());
            }
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_nuevaVenta = new javax.swing.JLabel();
        jLabel_VentasCiudad = new javax.swing.JLabel();
        jLabel_VentasCliente = new javax.swing.JLabel();
        jLabel_CuentasCobrar = new javax.swing.JLabel();
        jLabel_Admin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel_nuevaVenta.setText(" ");
        jLabel_nuevaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_nuevaVentaMouseClicked(evt);
            }
        });

        jLabel_VentasCiudad.setText(" ");
        jLabel_VentasCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_VentasCiudadMouseClicked(evt);
            }
        });

        jLabel_VentasCliente.setText(" ");
        jLabel_VentasCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_VentasClienteMouseClicked(evt);
            }
        });

        jLabel_CuentasCobrar.setText(" ");
        jLabel_CuentasCobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CuentasCobrarMouseClicked(evt);
            }
        });

        jLabel_Admin.setText(" ");
        jLabel_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_VentasCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_nuevaVenta))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_CuentasCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_VentasCiudad))
                .addGap(60, 60, 60)
                .addComponent(jLabel_Admin)
                .addContainerGap(1055, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nuevaVenta)
                    .addComponent(jLabel_VentasCiudad)
                    .addComponent(jLabel_Admin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_VentasCliente)
                    .addComponent(jLabel_CuentasCobrar))
                .addGap(289, 289, 289))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_nuevaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nuevaVentaMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        Factura fac = new Factura();
        fac.setTitle("Ingresar Nueva Factura");
        fac.setVisible(true);
    }//GEN-LAST:event_jLabel_nuevaVentaMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        client.cerrarSesion();
    }//GEN-LAST:event_formWindowClosing

    private void jLabel_VentasCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_VentasCiudadMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        VentasCiudad ventasCiudad = new VentasCiudad();
        ventasCiudad.setTitle("Ventas por ciudad");
        ventasCiudad.setVisible(true);
    }//GEN-LAST:event_jLabel_VentasCiudadMouseClicked

    private void jLabel_VentasClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_VentasClienteMouseClicked
        // TODO add your handling code here:
        VentasCliente ventasCliente = new VentasCliente();
        setVisible(false);
        ventasCliente.setTitle("Ventas por Cliente");
        ventasCliente.setVisible(true);
    }//GEN-LAST:event_jLabel_VentasClienteMouseClicked

    private void jLabel_CuentasCobrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CuentasCobrarMouseClicked
        // TODO add your handling code here:
        CuentasCobrar cuentasCobrar = new CuentasCobrar();
        setVisible(false);
        cuentasCobrar.setTitle("Cuentas por Cobrar");
        cuentasCobrar.setVisible(true);
    }//GEN-LAST:event_jLabel_CuentasCobrarMouseClicked

    private void jLabel_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AdminMouseClicked
        // TODO add your handling code here:
        Administrador admin = new Administrador();
        setVisible(false);
        admin.setTitle("Administrador");
        admin.setVisible(true);
    }//GEN-LAST:event_jLabel_AdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrincipalMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Admin;
    private javax.swing.JLabel jLabel_CuentasCobrar;
    private javax.swing.JLabel jLabel_VentasCiudad;
    private javax.swing.JLabel jLabel_VentasCliente;
    private javax.swing.JLabel jLabel_nuevaVenta;
    // End of variables declaration//GEN-END:variables
}
